### PR TITLE
Append new release to release list

### LINKED ISSUE #7: Keep version history
Is there any reason for not keeping a version history?
https://github.com/flathub/md.obsidian.Obsidian/blob/ab304eee8bdd13c940627d084a4b4478b80f5ca5/md.obsidian.Obsidian.appdata.xml#L23

You can check out how other packages do, for eg Riot:
https://github.com/flathub/im.riot.Riot/blob/4cf3b8265c94cb7c02e3e48a2b0e0f52ad3e7583/im.riot.Riot.appdata.xml#L26-L101

### PR DESCRIPTION
**Pull request by mamoit**
Instead of overwriting it.

Fixes #7

### CODE REVIEW

**Comment by joshua-stone** [comment]
This code doesn't seem to be editing the XML document as intended. How it appears after several runs:

```xml
  <releases>
    <release version="0.9.20" date="2020-12-7" />
  <release version="0.9.20" date="2020-12-7" /><release version="0.9.20" date="2020-12-7" /><release version="0.9.20" date="2020-12-7" /></releases>
```

**Comment by mamoit** [comment]
It seems to be valid xml though.
Let me see if I can improve the output though.

**Comment by joshua-stone** [comment]
It seems that information about previous versions isn't being retained.

**Before update:**

```xml
  <releases>
    <release version="0.9.17" date="2020-11-25" />
  </releases>
```

**After update:**

```xml
  <releases>
    <release version="0.9.20" date="2020-12-7" />
  <release version="0.9.20" date="2020-12-7" /></releases>
```

**Comment by mamoit** [comment]
@joshua-stone ah, that's bad indeed.

**Comment by mamoit** [comment]
@joshua-stone I'm importing the `update_release_date` function on an ipython console and it works as intended, no duplication of dates whatsoever.
Are you running multiple times with the same release number? Re-releasing a version.
If so, you can explore what for eg [debian does to their packages](https://manpages.ubuntu.com/manpages/xenial/man5/deb-version.5.html). They give it a revision number.
For eg, obsidian `0.9.20` is only called that on the 1st release, then it would be `0.9.20-1` and so on.
Otherwise it can be difficult for someone to report that they have an issue with version `0.9.20` of the flatpak, and you need to figure out which one :thinking:
It's still the same upstream code, just a different revision of the package.

**Comment by joshua-stone** [comment]
@mamoit Hello! Any more updates on this MR?

**Comment by joshua-stone** [comment]
Closing this PR as there hasn't been any activity for some time.

**Pull request closed without merging**
